### ISSUE TITLE
Lib editor: no delete item function

### ISSUE THREAD

**Issue by SaculRennorb** [LibrePCB/LibrePCB#310] opened 2018-08-20 20:25 UTC
##### LibrePCB VERSION
0.1.0 (first_pcb-655-g6b08041-dirty)
##### OS / ENVIRONMENT
win7x64

##### SUMMARY
well ... the lib editor has the delete item button permanently disabled
##### STEPS TO REPRODUCE
open the lib editor ^^ 
##### EXPECTED RESULTS
I'd like to at leaste have the option to delete an item from a lib
##### ACTUAL RESULTS
you cant delete lib items from the ui

**Comment by ubruhin** [comment] 2018-08-21 18:01
This is a duplicate of #200, see comments there how to delete a library element.

**Closed by ubruhin** 2018-08-21 18:01 UTC
