### ISSUE TITLE
Show actual grid settings

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#1368] opened 2024-04-04 21:02 UTC
##### SUMMARY
In the PCB/schematic/library editor I don't know actual grid settings till I enter to change it

##### SOLUTION
Show actual grid settings (numeric value of interval) for example near of XY coordinate of the cursor in the lower status area.

**Comment by ubruhin** [comment] 2024-04-04 21:50
Duplicate of #1051, thus closing.

**Closed by ubruhin** 2024-04-04 21:50 UTC
