### ISSUE TITLE
Bad icon for LibrePCB in Ubuntu (Microchip's one instead)

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#705] opened 2020-05-31 12:14 UTC
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.4
Git Revision:     ae04eef5a71b5ba66ae2cee6b631c1c933ace535
Build Date:       2020-05-02T18:50:04
Qt Version:       5.14.2 (built against 5.14.2)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.4 LTS
Platform Plugin:  xcb
```

##### SUMMARY
Logo is not the good one
![image](https://user-images.githubusercontent.com/7809481/83351623-ffecc780-a345-11ea-9fd5-43e8dabc8cd5.png)

##### STEPS TO REPRODUCE
1. launch LibrePCB
2. open Microchip library
3. lock screen with super+L
4. log back
Now icon is Microchip one and stay until lock screen again on another window

##### EXPECTED RESULTS
Always LibrePCB icon ?
But at least not Microchip icon when not on Microchip lib window.

##### ACTUAL RESULTS
Icon of Microchip instead of icon of LibrePCB

##### ADDITIONAL INFORMATION
Is it possible to have one icon for each window (not regrouped) ?
It will be easier to switch between all opened ones.
Or maybe a dropdown menu in the icon bar.

**Comment by ubruhin** [comment] 2020-06-01 19:50
Hmm yeah I also noted this strange behavior on Ubuntu some time ago, but I was not able to reproduce it on other operating systems. Thus I really don't know what we are doing wrong :( 

Maybe it's even just an Ubuntu bug?

**Comment by doom-fr** [comment] 2020-06-01 19:58
Maybe a bug in Ubuntu.

What icon should be displayed in theory for each window ?

**Comment by ubruhin** [comment] 2020-06-01 20:10
This is how it looks on Windows:

![grafik](https://user-images.githubusercontent.com/5374821/83449910-acb56a80-a454-11ea-9ae9-375002b605dd.png)

**Comment by Tubbles** [comment] 2020-12-27 14:15
I can reproduce this in Manjaro with XFCE, even no need to lock the screen
![image](https://user-images.githubusercontent.com/2370561/103172799-524b8380-4856-11eb-8cd2-406889ea6b40.png)

**Comment by ubruhin** [comment] 2023-04-15 20:40
I can't reproduce the problem with LibrePCB 0.1.7 on Ubuntu 22.04. Somehow the launcher always shows the LibrePCB logo, no matter which window is opened.

Anyway, generally it's intended that the library icon is used as window icon, to allow distinguishing between multiple opened libraries. How this is represented in a task bar is not really under our control, it's decided by the desktop environment.

So I don't know if there is any action needed on our side. I think it's fine as-is so I'll close this issue. If there are any objections, please reopen :)

**Closed by ubruhin** 2023-04-15 20:40 UTC
Labels: bug, os-linux, UI / UX
