### ISSUE TITLE
Segfault when re-opening project

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#432] opened 2019-03-17 23:23 UTC
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.0-unstable
Git Revision:     bc82905bb1b9abbee9ac4fc79018122e07a2c1be
Build Date:       2019-03-17T16:37:56
Qt Version:       5.12.1 (built against 5.12.1)
CPU Architecture: x86_64
Operating System: Arch Linux
Platform Plugin:  xcb
```

##### SUMMARY

When closing and re-opening a project, on re-opening the project LibrePCB segfaults.

##### STEPS TO REPRODUCE

Possibly this has to do with the user settings file.

Try this:

    echo "(librepcb_board_user_settings)" > boards/default/settings.user.lp

Then open the project, close it again and re-open it.

**Comment by ubruhin** [comment] 2019-03-18 21:36
I can't reproduce this... Can you reproduce it with the binaries from https://download.librepcb.org/nightly_builds/master/? If not, it might be a local build issue which could be fixed by a clean rebuild ;)

**Comment by dbrgn** [comment] 2019-03-19 14:39
Happens with the nightly AppImage too.

**Comment by ubruhin** [comment] 2019-03-19 19:33
Okay, strange. Could you get a stacktrace? I tried it on two machines, no crash...

**Comment by ubruhin** [comment] 2019-04-06 12:19
Removed from milestone 0.1.1 since it is not really reproducible. Or can we even close this issue?

**Comment by dbrgn** [comment] 2019-04-07 10:19
I'll try to find the cause sometime, but yeah, I don't think it's a widespread problem.

Let's keep it open for a while to see if someone else experiences this problem.

**Comment by alfishe** [comment] 2019-05-25 19:59
I believe that there should be global error/exception handler for all load/save/export/import operations so any error will just roll back to previous state (or just open GUI without project loaded if it's app (re)start). Segfault is not an option for user-friendly app.

**Comment by rnestler** [comment] 2019-06-17 08:37
> I believe that there should be global error/exception handler for all load/save/export/import operations so any error will just roll back to previous state (or just open GUI without project loaded if it's app (re)start). 

Segfaults normally don't have anything to do with C++ exception handling, but most of the time are caused by memory safety bugs. While one could theoretically [set up a handler for the SIGSEGV signal](https://stackoverflow.com/questions/2350489/how-to-catch-segmentation-fault-in-linux) on Linux, it is almost impossible to do anything without triggering undefined behavior which may lead to much worse behavior than just aborting.
What one could do is to start multiple processes, where one supervises the other and handles the case when it aborts.

> Segfault is not an option for user-friendly app.

Of course these bugs should be fixed :slightly_smiling_face: and I agree that they should have high priority to get fixed.

**Closed** 2019-11-11 19:53 UTC
Labels: bug
