### ISSUE TITLE
Arc Tool for Library Editor

### ISSUE THREAD

**Issue by brim2full** [LibrePCB/LibrePCB#800] opened 2020-10-29 12:09 UTC
##### SUMMARY
The library editor only has draw tools for: line, rectangle, polygon and circle.  An arc tool is required in order to draw such items as transformer symbols for 60617.  While it is possible to draw a line and then edit its properties (specifically angle) this is not an obvious approach.

##### SOLUTION
A quick and dirty.  Have the arc tool button use the line functionality directly but with the angle parameter set to say 90deg.  An improved / optimised properties dialogue box could follow later.

**Comment by dbrgn** [comment] 2020-10-29 12:33
Thanks, I agree! Duplicate of #354.

**Closed by dbrgn** 2020-10-29 12:33 UTC
