### ISSUE TITLE
Incomplete grid area shown if applied a scale factor to graphic drivers.

### ISSUE THREAD

**Issue by xotho** [LibrePCB/LibrePCB#1420] opened 2024-07-29 10:14 UTC
Windows 11 Pro platform.
Quadro RTX4000 ADA, drivers v555.99

As per title , here follow image examples : 

![image](https://github.com/user-attachments/assets/5bcd16d3-1212-4c57-9616-957482c0d79d)

![image](https://github.com/user-attachments/assets/2d70ebb4-4ff7-4af9-b8d7-5204da410ce0)

Applied scaling factor : 
 
![image](https://github.com/user-attachments/assets/2504cbee-1bad-437a-922b-410624657e46)

take care ,
X!

**Comment by xotho** [comment] 2024-07-29 10:28
Issue not present in this version:

![image](https://github.com/user-attachments/assets/d0d12b11-b3c8-4278-bcb7-f68e7357c5e9)

Sorry,
X!

**Comment by ubruhin** [comment] 2024-07-29 10:52
May the difference be 32-bit (Qt5) or 64-bit (Qt6) releases? On our [download page](https://librepcb.org/download/) we currently provide 64-bit Windows releases as BETA, maybe the bug doesn't exist in this build?

**Comment by xotho** [comment] 2024-07-29 11:04
The version that do not expose the issue already use v6.6.2 QT and it's a night build BETA.

![image](https://github.com/user-attachments/assets/c9639ad3-5db4-46e2-9c57-3c19fd204760)

LibrePCB Version: 1.1.1-unstable
Git Revision:     04485b3b5
Build Date:       2024-07-22T16:44:17
Build Author:     LibrePCB CI
Qt Version:       6.6.2 (built against 6.6.2)
CPU Architecture: x86_64
Operating System: Windows 11 Version 23H2
Platform Plugin:  windows
TLS Library:      OpenSSL 3.0.12 24 Oct 2023
OCC Library:      OCCT 7.7.2

// -------------------------------------------------------------------------------------------------------------------

The night build BETA that expose this issue uses v6.6.2 QT too, and it's : 

![image](https://github.com/user-attachments/assets/ceb939db-7e8c-4623-88dc-b95aa7dfea45)

LibrePCB Version: 1.1.1-unstable
Git Revision:     38facb33b
Build Date:       2024-07-25T11:15:46
Build Author:     LibrePCB CI
Qt Version:       6.6.2 (built against 6.6.2)
CPU Architecture: x86_64
Operating System: Windows 11 Version 23H2
Platform Plugin:  windows
TLS Library:      OpenSSL 3.0.12 24 Oct 2023
OCC Library:      OCCT 7.7.2

**Comment by ubruhin** [comment] 2024-07-29 11:41
`38facb33b` is not on `master` branch - please do NOT use non-master branches, they are incomplete and dangerous! And for real work, please don't even use nightly builds at all, only use stable releases. It's a lot of wastes time for us to investigate issues on development builds, which hinders us to work on new features etc. If this happens more often, I'll think about not providing nightly builds at all anymore.

Closing as the issue is not relevant.

**Closed by ubruhin** 2024-07-29 11:41 UTC
Labels: bug, UI / UX, tool-board-editor, tool-schematics-editor
