### ISSUE TITLE
Mirror/rotate actions produce offsets for the whole selected area

### ISSUE THREAD

**Issue by alfishe** [LibrePCB/LibrePCB#450] opened 2019-05-12 19:30 UTC
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.1-unstable
Git Revision: c14084c441
Qt Version: 5.12.0
Operating System: Windows 10 (10.0.17763 Build 17763)
...
```

##### SUMMARY
SchematicEditor: Mirror action produces offsets for the whole selected area. Offset errors are accumulated if multiple mirroring operations performed

##### STEPS TO REPRODUCE
1. Open "Demo Brushless Controller project"
2. Open schematic editor
3. Select rectangular area covering R29, R30, C22 and V_BATTERY net area
4. Press 'M' or perform mirror from Edit menu multiple times

##### EXPECTED RESULTS
On even number of sequential mirroring operations schematic fragment stays on same position with no shifts / offsets
![Screen Shot 2019-05-12 at 3 18 58 PM](https://user-images.githubusercontent.com/245354/57586904-9b589380-74ca-11e9-907b-31d72bc514e2.png)

##### ACTUAL RESULTS
On each mirror - fragment shifts left. Offset error accumulates on each mirror operation triggered
![Screen Shot 2019-05-12 at 3 19 16 PM](https://user-images.githubusercontent.com/245354/57586911-b75c3500-74ca-11e9-8b50-a8915c95191e.png)

##### ADDITIONAL INFORMATION
Seems related to mirror area center coordinates specifics. Instead of using boundary rectangle, mirroring command recalculates center based on items coordinates. Doesn't look and feel right

**Comment by ubruhin** [comment] 2019-05-13 19:11
This is strange indeed ;) 

I think the same issue exists in the board editor, and probably also in symbol and package editors.

**Comment by ubruhin** [comment] 2024-11-30 09:26
I can't reproduce this anymore with the current `master` version, probably this has been resolved in the mean time. Thus closing.

**Closed by ubruhin** 2024-11-30 09:26 UTC
Labels: bug, UI / UX
