### ISSUE TITLE
Schematic Editor : update net name when changing value of Vcc component

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#546] opened 2019-10-14 11:31 UTC
##### SUMMARY
When you add a Vcc (or any component that forced the net according to value field), it forces the net name to the value field.
![image](https://user-images.githubusercontent.com/7809481/66747716-76a38600-ee85-11e9-88af-bbc990e7dc8a.png)

But when you change the value field of the component, the net name is not updated : 
![image](https://user-images.githubusercontent.com/7809481/66748073-81124f80-ee86-11e9-947c-37793fc5324b.png)

You have to delete part of the net to get the good name : 
![image](https://user-images.githubusercontent.com/7809481/66748092-95eee300-ee86-11e9-9ae0-b6c5db805bae.png)

So when having change the value field, you have to delete a part of the wire and redraw it.

##### SOLUTION
update the net name when changing the value field.

**Comment by ubruhin** [comment] 2019-10-14 19:44
Duplicate of #466.

**Closed by ubruhin** 2019-10-14 19:44 UTC
