### ISSUE TITLE
Right panel in library editors is not resizable

### ISSUE THREAD

**Issue by BuFran** [LibrePCB/LibrePCB#1244] opened 2023-10-02 14:10 UTC
##### SUMMARY
On board, schematic and library listbox editors, there is size gripper where the user 
can resize the right side panel to his needs.  Especially on large 4K monitors the side 
panel is so big.

It could be better, if entire app behaves same way, so the library part, symbol, etc editors can 
have same gripper as board/schematic have.

(note)

The better will be to have this right panel completely floating if user wants this on different 
monitor, and by default it should be placed on right dock with implicit size gripper. But I 
understand that this is bigger change in internals (the editor then should have its own 
component that will be referenced in editor contexts instead of editorContext) and it 
is harder to implement. This separation will make this app better testable anyway.

##### SOLUTION
Add size gripper to *.ui files to enable sizing feature.

**Comment by ubruhin** [comment] 2023-10-02 14:17
Duplicate of #815, thus closing this.

Note that a major UI refactoring is planned anyway so at the moment it makes no sense to work just on this issue on the current code base as it would become obsolete soon...

**Closed by ubruhin** 2023-10-02 14:17 UTC
