### ISSUE TITLE
STEP export: Wrong device placement for models with non-zero transform

### ISSUE THREAD

**Issue by xotho** [LibrePCB/LibrePCB#1387] opened 2024-05-08 15:01 UTC
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 1.1.1-unstable
Git Revision:     4d05a631f
Build Date:       2024-05-06T08:58:42
Build Author:     LibrePCB CI
Qt Version:       6.6.2 (built against 6.6.2)
CPU Architecture: x86_64
Operating System: Windows 11 Version 23H2
Platform Plugin:  windows
TLS Library:      OpenSSL 3.0.12 24 Oct 2023
OCC Library:      OCCT 7.7.2

##### SUMMARY
Exported 3D-STEP show a PCB where a component mounted on BOTTOM side of the PCB is turned 180 degree.
In the LibrePCB all is shown correctly instead.

Wrong location about exported: 
![image](https://github.com/LibrePCB/LibrePCB/assets/2029366/49297259-8e24-4f67-b1f1-7c2962494bc2)

Right position shown in LibrePCB:
![image](https://github.com/LibrePCB/LibrePCB/assets/2029366/02878d85-7a8e-41bc-907b-b1cfaa384a2b)

**Comment by ubruhin** [comment] 2024-05-10 06:46
I don't understand from the pictures what is wrong. It doesn't even look like the same PCB is shown in both pictures :thinking: 

Can you please post the whole project (or send it to the contact email address on the website)?

**Comment by xotho** [comment] 2024-05-10 11:13
Dear ubruhin,

check the following images, ( I removed some components ):

1)
![image](https://github.com/LibrePCB/LibrePCB/assets/2029366/b9d7011d-808e-4de7-8967-2ff00e955dc7)

exported and imported in FREECAD or PTC:

2)
![1715339396134](https://github.com/LibrePCB/LibrePCB/assets/2029366/c7a46872-43f6-47d4-be4b-8ecd009fadb1)

1) is the right view in LIBREPCB, 2) is the wrong view imported in FREECAD or PTC.

Should be clear I think.

Do you need more ?

**Comment by ubruhin** [comment] 2024-05-14 05:02
I still cannot reproduce this, it would be very helpful to have your project for investigation. If you send it (as *.lppz export) to the contact email on our website, I'll handle it confidentially.

**Comment by xotho** [comment] 2024-05-14 07:28
Pls Check **contact** Email.

take care

**Comment by ubruhin** [comment] 2024-05-14 10:03
Got it, and can reproduce it! Thank you!

**Comment by xotho** [comment] 2024-05-14 10:07
Great. Thank you 2 U.

**Comment by ubruhin** [comment] 2024-06-11 09:24
OK this is really strange... The affected STEP model is a bit unusual because it contains a rotation of 180°, as shown in the FreeCAD object inspector:

![image](https://github.com/LibrePCB/LibrePCB/assets/5374821/0ee8de57-596e-4ea3-867b-f5a50eb755c6)

But of course also this unusual case needs to be supported properly by LibrePCB. However, after exporting the PCB to STEP, this rotation is lost on the package:

![image](https://github.com/LibrePCB/LibrePCB/assets/5374821/1413298d-609d-45de-8349-8e1e93466ded)

I don't know why this happens, but I realized it can be fixed with a small change (see #1401). The output structure is then as expected:

![image](https://github.com/LibrePCB/LibrePCB/assets/5374821/2a83222e-0e17-4345-9221-225e91dcb8c9)

And even the label "DEV1:1" is now correct, although this makes absolutely no sense to me. Also the change in #1401 makes no sense to me, but at least I didn't experience any negative impact on several projects I tested. That's the mystery of the OpenCascade API which I still don't understand at all...

I think we can go with this change for now and if any new issue pops up in future we have to investigate it again.

@xotho would be nice if you could test your project with the nightly build of #1401 (should appear in ca. an hour) and report here if the exported STEP is now correct.

**Closed** 2024-06-14 11:49 UTC
Labels: bug, export
