### ISSUE TITLE
Library Editor Crash (SegFault) when editing Pins

### ISSUE THREAD

**Issue by bcallebaut** [LibrePCB/LibrePCB#485] opened 2019-07-18 12:48 UTC
I am on Debian 9.8 - 64 bits.
I use  the latest librepcb version released.
When I try to assign pins in a component, LibrePCB crashes with a segmentation Fault.

**Comment by bcallebaut** [comment] 2019-07-18 12:56
Duplicate of #225. Qt 5.7.1

Tested with Qt 5.12.4 and no bug.

**Comment by ubruhin** [comment] 2019-07-23 20:58
Could you please report the bug with our issue template? It's impossible to understand and reproduce a bug without knowledge about your environment and steps to reproduce. The system information is available in LibrePCB's About dialog, just copy&paste that to the issue description.

**Comment by ubruhin** [comment] 2020-09-13 13:11
Closing this because it was reported a long time ago with an older LibrePCB version and without clear instructions how to reproduce it. Feel free to reopen if the issue still exists with the latest LibrePCB release.

**Closed by ubruhin** 2020-09-13 13:11 UTC
Labels: bug
