### ISSUE TITLE
There is no uninstaller?!!

### ISSUE THREAD

**Issue by jruk** [LibrePCB/LibrePCB#695] opened 2020-05-03 01:41 UTC
After installation on OSX 10.12.6 it appears that:
1) There is no LibrePCB in the Application folder
2) There is no way whatsoever to uninstall the app

Please provide at least a terminal command or instructions allowing us to remove the software.

**Comment by ubruhin** [comment] 2020-05-03 16:27
> There is no LibrePCB in the Application folder

Maybe that's caused by #644? If yes, that's fixed in LibrePCB 0.1.4 which was released today.

> There is no way whatsoever to uninstall the app

Yes there is :wink: Beside the LibrePCB application, the installer also installs the "LibrePCB Maintenance Tool" which allows you to update or uninstall LibrePCB.

Btw, for support requests please use our [forum](https://librepcb.discourse.group/) instead of this issue tracker.

I'll close this issue. Feel free to reopen if you think there is really a bug in our installer.

**Closed by ubruhin** 2020-05-03 16:27 UTC
