### ISSUE TITLE
Library Editor / Symbol : Up/down arrows behavior

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#708] opened 2020-06-02 22:12 UTC
##### SUMMARY
Usually in LibrePCB, up and down arrows multiply/divide by 2 the value of the associated field
But in library editor / symbol, it add/subtract 2.54mm
Why not ! But when grid is 1.27mm, it also add/subtract 2.54mm

##### SOLUTION
Take in account the size of the grid to know the increment/decrement value
(when grid is 1.27mm, increment/decrement of 1.27mm, not 2.54mm)

**Comment by ubruhin** [comment] 2023-02-21 12:41
I cannot reproduce this with LibrePCB 0.1.7, probably it was already fixed in the mean time :see_no_evil: Feel free to reopen if I'm wrong.

**Closed by ubruhin** 2023-02-21 12:41 UTC
