### ISSUE TITLE
Illumos: Qt signals don't work

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#913] opened 2021-09-15 22:40 UTC
When building LibrePCB on Illumos (OpenIndiana):

```
$ mkdir build && cd build
$ CMAKE_PREFIX_PATH=/usr/lib/qt/5.12/ cmake .. -DCMAKE_BUILD_TYPE=Debug
$ make -j 20
```

![image](https://user-images.githubusercontent.com/105168/133518883-2d50afdd-5dc0-4bef-b318-b3b9551b1c90.png)

...and running the resulting binary, the signals don't seem to work.

![image](https://user-images.githubusercontent.com/105168/133519067-9ec68dfc-399f-4bf3-8e4a-3dd7ece86130.png)

"QObject::connect: signal not found in QPushButton (:0)"

Even though the text field is filled out, the button is still greyed out. See also the highlighted warnings on the left.

This did not happen with the old qmake based setup, so it may be related to some build system details in combination with Illumos 😕 LTO is not being used, as far as I can tell.

(Maybe @Toasterson knows something?)

**Comment by Toasterson** [comment] 2021-09-16 14:39
We had some events not being passed to glib/HAL some time ago but only USB connect events. Keystrokes worked always for other Languages... And I am not aware of other QT applications having problems. 

Is the build system skipping this because of some missing library or a header type we have differently than other OSes? I know we get Problems in other C++ apps because our int8_t is implicit signed char rather than explicitly signed char

**Comment by ubruhin** [comment] 2022-09-18 17:45
I tried to reproduce this with the latest OpenIndiana release. Everything seems to work, no problem with signals&slots anymore! :rocket: 

![image](https://user-images.githubusercontent.com/5374821/190921053-27b8007d-b005-4478-a903-940e7b470f01.png)

Probably the issue was not on our side, so let's close it.

**Closed by ubruhin** 2022-09-18 17:45 UTC
Labels: bug, build system
