### ISSUE TITLE
Library editor: Changes in text field with focus not saved when closing tab

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/LibrePCB#492] opened 2019-08-05 16:16 UTC
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.2
Git Revision:     acdd94d9d2310f79215125b999153e9da88a9376
Build Date:       2019-07-13T21:11:00
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.10
Platform Plugin:  xcb
```

##### SUMMARY
Does not prompt to save after library changes are made

##### STEPS TO REPRODUCE
- Edit a library part
- change the description
- close tab

##### EXPECTED RESULTS
it should prompt to save data

##### ACTUAL RESULTS
data lost

##### ADDITIONAL INFORMATION
If you change the description AND the keywords then it will prompt. It only
fails if a single thing is changed

**Comment by ubruhin** [comment] 2019-08-09 21:39
The problem is that changes in text fields are applied when it looses the focus. You don't have to modify two things, it's sufficient to click somewhere outside the text field to get the changes applied.

Anyway, I agree it's not user friendly and should be fixed if possible.

**Closed** 2019-10-27 09:53 UTC
Labels: UI / UX, bug
