### ISSUE TITLE
AppImage for 0.1.7 doens't run on KDE Neon

### ISSUE THREAD

**Issue by ilario-gottardello** [LibrePCB/LibrePCB#1140] opened 2023-03-29 12:14 UTC
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 0.1.7, AppImage package
Git Revision:
Qt Version:
Operating System: KDE Neon based on Ubuntu 22.04

##### SUMMARY
Just downloaded from librepcb.org, executed from shell

##### STEPS TO REPRODUCE
Open a terminal and run ./librepcb-0.1.7-linux-x86_64.AppImage

##### EXPECTED RESULTS
Program starts

##### ACTUAL RESULTS
Program exit with this output:
"execv error: No such file or directory"

##### ADDITIONAL INFORMATION
libfuse is present on the system. This is a fresh installation of the operating system, updated to today. I use appimagelauncher from his ppa for AppImages integration.

dpkg -l | grep libfuse
ii  libfuse2:amd64                                2.9.9-5ubuntu3                                 amd64        Filesystem in Userspace (library)
ii  libfuse3-3:amd64                              3.10.5-1build1                                 amd64        Filesystem in Userspace (library) (3.x version)

**Comment by ubruhin** [comment] 2023-03-29 15:27
Just to confirm, you set the executable flag on the AppImage prior to execution, right?

At least I cannot reproduce the problem. I just downloaded the latest KDE Neon, started it as a live system in VirtualBox, downloaded the 0.1.7 AppImage, set the executable flag and it runs as expected:

![image](https://user-images.githubusercontent.com/5374821/228588660-2b861255-2125-429c-969a-28a898127a61.png)

Since you mentioned appimagelauncher, maybe that's the reason for the problem? Could you try running it just plain, without appimagelauncher? Maybe this tool either modifies our AppImage prior to execution, or runs it in a different way? Otherwise I have no idea why it works for me, but not on your system :(

**Comment by ilario-gottardello** [comment] 2023-03-29 20:03
Yes, the executable flag is set, and.... yes, the guilty one is appimagelauncher. I removed it and the AppImage starts happily.... I think I have to file a bug report to them! Thank you very much

**Comment by ubruhin** [comment] 2023-03-29 20:46
OK good to know! :+1:

So it sounds like the problem is not on our side, thus I'll close this issue for now. Please don't hesitate to reopen if there is any indication that we need to change something on our side.

**Closed as not planned** 2023-03-29 20:46 UTC
Labels: deployment, os-linux
