### ISSUE TITLE
Pin Name Spacing Parameter

### ISSUE THREAD

**Issue by brim2full** [LibrePCB/LibrePCB#882] opened 2021-04-07 06:12 UTC
##### SUMMARY
Library Schematic Symbol Editor:  Separate the pin line length parameter from the pin name distance.  Would eliminate this issue:
![Text Spacing](https://user-images.githubusercontent.com/73645498/113818913-0b7bfc80-9768-11eb-962b-e7e3eb73d31a.PNG)

**Comment by ubruhin** [comment] 2021-04-11 09:17
Duplicate of #383.

**Closed by ubruhin** 2021-04-11 09:17 UTC
